# all:
  # afStudio:
    # console_cli: '/opt/local/bin/php'
    # console_commands: ['mkdir', 'ls', 'll', ]
    # console_aliases: {'ll': 'ls -l', }
all:
  afs:
    # use this to set the production:false/development:true environment of Studio
    debug: true
    # When you disable projects management - create/load/recent project items 
    # in studio toolbar will not be available
    projects_management_enabled: true
    
    # Configuration for ServerEnvironment class
    server_auto_vhost_creation_enabled: false
    server_env_studio_project_vhosts_dir: /etc/httpd/studio_projects_vhosts
    server_env_apachectl_path: /usr/sbin/apachectl
    # If domain suffix is not provided created vhosts will use different port numbers
    # Otherwise it will be always 80 port with URL's like SLUG.DOMAIN_SUFFIX
    # server_auto_vhost_domain_suffix: demo.appflower.com
    