# all:
  # afStudio:
    # console_cli: '/opt/local/bin/php'
    # console_commands: ['mkdir', 'ls', 'll', ]
    # console_aliases: {'ll': 'ls -l', }
all:
  afs:
    # use this to set the production:false/development:true environment of Studio
    debug: false
    # To have "Projects management" enabled you need to have access to properly configured
    # appFlowerService project instance
    # check that project README.md file for more details
    projects_management_enabled: false
    # if you enable projects management - provide url to api
    # afServiceUrl: api.appflower.com
    
    # If domain suffix is not provided created vhosts will use different port numbers
    # Otherwise it will be always 80 port with URL's like SLUG.DOMAIN_SUFFIX
    # server_auto_vhost_domain_suffix: demo.appflower.com
    