template:
  default: desktop
  types: [ desktop, viewport ]
  helpers:
    desktop: 
      - [cssEditor, 'CSS Editor', template_editor_default.png, afStudio.CssEditor]
      - [afExtjsDesktopStartMenu, 'Start Menu Editor', template_editor_default.png, afStudio.BaseEditor]
      - [afExtjsDesktopLinks, 'Desktop Links Editor', template_editor_default.png, afStudio.BaseEditor]
    viewport: 
      - [cssEditor, 'CSS Editor', template_editor_default.png, afStudio.CssEditor]
      - [afExtjsToolbar, 'Menu Toolbar Editor', template_editor_default.png, afStudio.BaseEditor]
      - [afExtjsWest, 'West Panel Editor', template_editor_default.png, afStudio.BaseEditor]
      - [afExtjsSouth, 'South Panel Editor', template_editor_default.png, afStudio.BaseEditor]
      - [afExtjsEast, 'East Panel Editor', template_editor_default.png, afStudio.BaseEditor]